[package]
name = "echomap"
version = "0.1.0"
authors = ["Pat Sier <pjsier@gmail.com>"]
description = "A command line tool for previewing map files in the console"
readme = "README.md"
repository = "https://github.com/pjsier/echomap"
license = "MIT"
edition = "2018"

[dependencies]
geo = "0.12"
geo-types = { version = "0.4", features = ["rstar"] }
geojson = { version = "0.16", features = ["geo-types"] }
num-traits = "0.2"
rstar = "0.5"
console = "0.8.0"
indicatif = "0.11.0"
clap = "2.33.0"

[[bin]]
name = "echomap"
path = "src/main.rs"
