[package]
name = "echomap"
version = "0.1.0"
authors = ["pjsier <pjsier@gmail.com>"]
edition = "2018"

[dependencies]
geo = "0.12.1"
geo-types = { version = "0.4.2", features = ["rstar"] }
geojson = { version = "0.16.0", features = ["geo-types"] }
num-traits = "0.2"
rstar = "0.2.0"
console = "0.8.0"
