name: Release

on:
  push:
    tags:
      - '*'

jobs:

  publish-crate:

    name: Publish crate

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-release:

    name: Publish release for ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:

      matrix:

        os: [ubuntu-latest, windows-latest, macos-latest]

        include:

          - os: ubuntu-latest
            artifact_name: echomap
            asset_name: echomap-linux-amd64

          - os: windows-latest
            artifact_name: echomap.exe
            asset_name: echomap-windows-amd64

          - os: macos-latest
            artifact_name: echomap
            asset_name: echomap-macos-amd64

    steps:

      - uses: hecrj/setup-rust-action@v1-release
        with:
          rust-version: stable

      - uses: actions/checkout@v1

      - name: Build
        run: cargo build --release --locked

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
